### ISSUE TITLE
Component Styling

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#11]
## Value Proposition

As a Developer
I want to implement styled components 
so that my styling is tidier and easier to work with! 
​

## Description

(... styled components over global css styling)
​

## Acceptance Criteria

- [ ] components are styled via the component-styling method

## Tasks

- [ ] review the topic "styled components"
- [ ] change the temporary styling
