### ISSUE TITLE
Styled Navbar (active link)

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#12]
## Value Proposition

As a User 
I want to see the active link on the navigation  
so that it is easier to locate on which page I am! Also I would like to switch back to the homepage via a Click on the Logo!
​
## Description

Active page is designed eye-catching:
![styled_nav](https://user-images.githubusercontent.com/123374352/229528208-4cc09722-9019-40b0-ac1f-edaf5e1d0517.jpg)

## Acceptance Criteria

- [ ] if you follow one of the navbar-links, the one that's currently active (active page) is somehow highlighted (via underline / color / size etc)
- [ ] there is a Logo to click on to get back to the homepage
      ​

## Tasks

- [ ] add styling to an active link
- [ ] more styling to the navbar
- [ ] implement Logo
- [ ] styling with styled components (need to change)
      ​

**Comment by manukao** [comment]
lgtm 🙂

**Comment by NinaBusz** [comment]
> lgtm 🙂

Thank you! 😍
