### ISSUE TITLE
#1 :pencil: homepage & form

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#2]
## homepage and form

As an user, I would like to have an interface on which I can write down my flashes of inspiration/ideas directly and without many clicks/obstacles and somehow save them.
​
## Description

![form](https://github.com/NinaBusz/Capstone-Project/blob/main/assets/sketches/form.PNG?raw=true)
​

## Acceptance Criteria

- [ ] there is a text field on the home page
- [ ] I should be able to type in the text field without hindrance 
- [ ] you can save the text
- [ ] the text field should be able to be reset to an empty state with one click
      ​

## Tasks

- [x] a form directly visible on the homepage
- [x] an input field with a placeholder (e.g. "type here")
- [x] label "fixe Ideen"
- [x] button (submit) for saving - only if theres written sth.
- [x] button to empty the text field fast
- [x] minimal styling
      ​
