### ISSUE TITLE
#2 :heavy_minus_sign: page to list

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#3]
## list of ideas

As a user, I would like a page with a list where I can see all my ideas sorted by date and where I can delete them.
​

## Description

![list](https://github.com/NinaBusz/Capstone-Project/blob/main/assets/sketches/list.png)
![listdetail](https://github.com/NinaBusz/Capstone-Project/blob/main/assets/sketches/list_detail.JPG)
​

## Acceptance Criteria

- [ ] new page "/ideas"
- [ ] theres a list with the saved ideas, sorted by date
- [ ] you can delete ideas
- [ ] shown date
      ​

## Tasks

- [x] make a new page
- [x] need to show the ideas in local storage in a list
- [x] button delete ideas
- [x] reverse list

      ​
