### ISSUE TITLE
#3 Navbar

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#4]
## Navbar

As a User i want a navigation on top of the page so i can get access to all pages. 

## Description

![navigation](https://github.com/NinaBusz/Capstone-Project/blob/main/assets/sketches/navbar.PNG)
​

## Acceptance Criteria

- [ ] naviagtion thats reachable on all pages
- [ ] can navigate from each page to the other page
      ​

## Tasks

- [x] navgiation-component
- [x] links to homepage, ideas-list
      ​
