### ISSUE TITLE
US project area

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#8]
## Value Proposition

As a user, I would like to have a project area where I can create and edit projects.
​

## Description

empty list:
![projectslist_noentry](https://user-images.githubusercontent.com/123374352/227898685-11dd6126-ed0c-4745-a0d1-e01b3aa5ae1c.JPG)
list:
![projectslist](https://user-images.githubusercontent.com/123374352/227898670-80c033bb-475e-41b5-8e53-4eb76efaac9c.JPG)
details-page:
![projectdetailspage](https://user-images.githubusercontent.com/123374352/227901261-6e1661fb-6302-48b4-9b27-d5ce8c4284b5.jpg)

## Acceptance Criteria

- [ ] there is a projects page with a list of projects, if no project, there is just a button "neues projekt erstellen" in same size as the project preview pic
- [ ] You can create new projects by clicking on that button 
- [ ] project-title should be shown in list on projects-page and there should be a placeholder-image as the project preview
- [ ] if you click on the project prev-pic, you are in the area of the project (detailspage)
- [ ] You can then pick a title and a description on the project-details-page 
- [ ] You can add an image-url 

​

## Tasks

- [ ] new page "projects" (to list the projects)
- [ ] button for new project 
- [ ] project pages (dynamic routing)
- [ ] form component for each project with title / description /image-url input-field
- [ ] update Navbar ("Projekte")

**Comment by salaos** [comment]
I really like your scribble and the idea!
I have some thoughts about this user story:

- in the scribble I cannot see a "new project" button, would be helpful to know where it is placed
- how does the screen look like when there's no project created yet? Is there a default text or an empty screen? Or maybe a default picture of the mole, I like this little guy

**Comment by NinaBusz** [comment]
Thank you @salaos !! :)  
I modified the story based on your suggestions; hopefully readers can understand the US better now!
