### ISSUE TITLE
US #5 move ideas

### ISSUE THREAD

**Issue by NinaBusz** [NinaBusz/Ideas#9]
## Value Proposition

As a User I want to move my ideas
so that I can assign them to the projects. 
​

## on ideas-list:
![ideas.ist](https://user-images.githubusercontent.com/123374352/229431408-4a13deef-ba4c-4b5e-817b-67aaf3bca62d.JPG)

## ideaslist after clicking "verschieben"-button:
![Iideaslist-detail](https://user-images.githubusercontent.com/123374352/229431410-5bdcb6bb-d300-4a89-997c-bfe8cb46ba58.JPG)

## In project:
![projectarea-projekt-detail](https://user-images.githubusercontent.com/123374352/229431402-4cd265d0-23e2-42cd-92d7-a25e882aeb75.JPG)

​

## Acceptance Criteria

- [ ] button near the delete-button in the ideaslist "verschieben"
- [ ] if clicked you should be able to pick a projekt by name
- [ ] if one project is clicked, the idea is assigned to that project!
- [ ] the idea is not deleted from the original list (in case you have clicked the wrong project). However, you can still manually delete it from the original list
- [ ] idea is then listed in a list on the projekt-details-page below the description-area 
      ​

## Tasks

- [ ] new button below each created idea with an onclick-event that opens a hidden area
- [ ] in hidden area a list with each created project by name (idea should be listed in the picked project)
- [ ] new list of ideas in the project-details-page
      ​

**Comment by nikokreissl** [comment]
Looking great! 🙂
One small comment about acceptance criteria - on click of the project is the idea assigned to it? And afterwards the user can view it on the corresponding project?
Maybe you can add this to the acceptance criteria 😊

**Comment by NinaBusz** [comment]
ty for your comment!! 😃  I edited that part in the acceptance criteria!
